def menu():
    print("\n ********************")
    print("  ***Merge mail***  ")
    print("[1] Admin")
    print("[2] Upload")
    print("[3] Update")
    print("[4] Delete")
    print("[5] DB ")
    print("[6] Exit ")
    print("  ***Merge mail***  ")
    print("********************\n")
